[package]
name = "physics_in_parallel"
version = "3.6.0"
edition = "2024"
description = "High-performance infrastructure for numerical simulations in physics"
license = "MIT"
readme = "README.md"
repository = "https://github.com/dingyisun0101/Physics-in-Parallel"
homepage = "https://github.com/dingyisun0101/Physics-in-Parallel"
documentation = "https://docs.rs/physics_in_parallel"
keywords = ["physics", "simulation", "math", "tensor", "scientific"]
categories = ["science"]
rust-version = "1.97"
exclude = ["target/", ".git/", ".idea/", ".vscode/"]

[dependencies]
# Number traits (real + complex)
num-traits = "0.2"
num-complex = { version = "0.4", features = ["serde"] }

# Random number generation
rand = "0.10.1"
rand_distr = "0.6"
rand_chacha = "0.10"
rand_pcg = "0.10.2"

# Automatic parallelism
rayon = "1.12"

# Fast hash maps
ahash = "0.8"

# IO
serde = { version = "1.0", features = ["derive"] }
erased-serde = "0.4"
serde_json = { version = "1.0", features = ["float_roundtrip", "raw_value"] }
ndarray = "0.17"


[profile.release]
opt-level = 3
lto = true
codegen-units = 1
